config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check
  
  devise_scope :user do
    root to: 'devise/sessions#new'  # Devise login page
  end
  

  resources :posts do #this line replaces all the routes below
    resources :comments, only: [:create, :destroy]
  end
  
  # get "/posts/new" => "posts#new"
  # get "/posts/:id/edit" => "posts#edit"
  # get "/posts/:id" => "posts#show"
  # patch "/posts/:id" => "posts#update"
  # delete "/posts/:id" => "posts#destroy"
  # post "/posts" => "posts#create" 
  
  # root "posts#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :name, :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, dependent: :destroy #realationship to comments. if post is deleted, comments are deleted
    validates :title, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  def after_sign_in_path_for(resource)
    posts_path  # Redirects to posts index page
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.build(comment_params)  ##use build instead create so it would not save to the database yet

        if @comment.save
            redirect_to @post, notice: "Comment was successfully created."
        else
            redirect_to @post, alert: "Comment was not created."
        end
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy

        redirect_to @post, notice: "Comment was successfully deleted."
    end

    private

    def comment_params
        params.require(:comment).permit(:name, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  # def show
  # end

  def new
    @post = Post.new
  end

  def create   
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  # def edit
  # end

  def update
    if @post.update(post_params)
        redirect_to @post
    else
        render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @post.destroy
      flash[:notice] = "Post was successfully deleted."
    else
      flash[:alert] = "Failed to delete the post."
    end
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

    def set_post
        @post = Post.find(params[:id])
    rescue ActiveRecord::RecordNotFound ##error handling
        redirect_to root_path ##redirect to the root path if the record is not found
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<div class="comment-form-container">
<hr style="border: none; height: 2px; background-color: gray; margin-bottom: 1rem; ">

<h3>Add a Comment:</h3>

  <%= form_with model: [@post, Comment.new], local: true, class: "comment-form" do |form| %>
    <div class="form-group">
      <%= form.label :name, "Your Name", class: "form-label" %><br>
      <%= form.text_field :name, class: "form-input" %>
    </div>

    <div class="form-group">
      <%= form.label :body, "Your Comment", class: "form-label" %><br>
      <%= form.text_area :body, class: "form-textarea" %>
    </div>

    <%= form.submit "Post Comment", class: "form-submit" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Blog Project" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body >
  
  <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    
    <%= yield %>
    <div class="header">
    
      <% if user_signed_in? %>
        
        <%= link_to "Logout", destroy_user_session_path, 
                              method: :delete, 
                              data: {turbo_method: :delete}, 
                              class: "logout-btn" %>
      
      <% end %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post do |form | %>
    <% if form.object.errors.any? %>
      <div class="error-messages">
          <% form.object.errors.full_messages.each do |msg| %>
              <li class="error-message"><%= msg %></li>
          <% end %>
      </div>
    <% end %>
    <p>
      <%= form.label :title, class: "form-label" %><br>
      <%= form.text_field :title, class: "form-input" %>
    </p>
  
    <p>
      <%= form.label :body, class: "form-label" %><br>
      <%= form.text_area :body, class: "form-textarea" %>
    </p>
  
    <p>
    <%= form.submit "Submit", class: "form-submit" %>
    <% if show_delete_button %>
      <%= button_to "Delete Post", post_path(@post), 
                                   method: :delete, 
                                   data: { turbo_confirm: "Are you sure?", turbo: false }, 
                                   class: "delete-post-btn" %>
    <% end %>
    </p>
  <% end %>

app/views/posts/edit.html.erb
<h1>Edit Blog Post</h1>

<%= render partial: "form", locals: {post: @post, show_delete_button: true } %>

<%= link_to "Back", post_path(@post) %>


app/views/posts/index.html.erb
<div style="text-align: center; margin-top: 20px;">
    <h1 class="header-title-post">Post</h1>
    <h1 class="header-title-hub">Hub</h1>
    <h3>A simple blog project using Ruby on Rails</h3>
</div>

<% @posts.reverse.each do |post| %>
    <div class="post-index">
        <h2><%= link_to post.title, post %></h2>
        <p class="created-at">
            <%= post.created_at.in_time_zone(Time.zone.name).strftime("%m-%d-%y %I:%M") %></p>
        <p><%= post.body %></p>
    </div>
<% end %>

<%= link_to "Create New Post", new_post_path, class: "new-post-btn" %>

app/views/posts/new.html.erb
<h1 class="newh1">New Blog Post</h1>

<%= render partial: "form", locals: {post: @post, show_delete_button:false} %>
<%= link_to "Back", root_path %>

app/views/posts/show.html.erb
<h1 class="blog-title"><%= @post.title %></h1>
<p class="created-at"><%= @post.created_at.in_time_zone(Time.zone.name).strftime("%m-%d-%y %I:%M") %></p>
<p class="blog-text"><%= @post.body %></p>

<h2>Comments</h2>
<div class="comments-div">
  <% @post.comments.each do |comment| %>
    <p> <i>"<%= comment.body %>" </i>-<strong><%= comment.name %></strong> 
    <span style="font-size: 12px"> <%= comment.created_at.in_time_zone(Time.zone.name).strftime("%m-%d-%y %I:%M") %></span></p>
    <!-- <%= link_to "Delete comment", post_comment_path(@post, comment), 
    method: :delete, data: { confirm: "Are you sure?" }, class: "delete-comment-link" %> -->
  <% end %>
</div>

<%= render "comments/form", post: @post %>

<div class ="edit">
    <%= link_to "Edit Post", edit_post_path(@post) if user_signed_in? %>
    <%= link_to "Back", root_path %>
</div>